name: Deploy

on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  deploy-app:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: yarn

      - name: Deploy
        run: yarn deploy
